import type { NextPage } from "next";
import Head from "next/head";
import { Intro } from "../components/Intro";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>manmodesanket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-one.ico" />
      </Head>
      <Intro />
    </div>
  );
};

export default Home;
