import type { NextPage } from "next";
import Head from "next/head";
import { Header, Intro } from "../components/Intro";
import { useData } from "../context/DataContext";

const Home: NextPage = () => {
  const {
    data: { mode },
  } = useData();
  return (
    <div className={mode === "moon" ? "dark" : ""}>
      <Head>
        <title>manmodesanket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-one.ico" />
      </Head>
      <div className="w-full min-h-screen bg-white dark:bg-slate-800 dark:text-white">
        <Header />
        <Intro />
      </div>
    </div>
  );
};

export default Home;
